name: CI/CD

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            simoneverhagen/student-app:latest

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: test
        run: |
          docker run -d -p 80:5000 simoneverhagen/student-app:latest
          sleep 10s
          curl http://localhost
          docker ps -aq | xargs docker stop | xargs docker rm

  deploy:
    name: Deploy
    needs: [test]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Use existing registry secret for all pods
        run: |
          sudo kubectl -n default patch serviceaccount default \
            --type='strategic' \
            -p '{"imagePullSecrets":[{"name":"my-registry-secret"}]}'

      - name: Apply manifests
        run: |
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/deployment.yaml
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/nginx-service.yaml

      - name: Rollout new image
        env:
          IMAGE: simoneverhagen/student-app:${{ github.sha }}
        run: |
          sudo kubectl set image deployment/student-devsecops quoterxp=$IMAGE
          sudo kubectl rollout status deployment/student-devsecops --timeout=180s
